### ISSUE TITLE
Error sending notifications for new registered user

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#261]
It seems there's a mismatch in notice type

```
pinax.notifications.models.NoticeType.DoesNotExist: NoticeType matching query does not exist.
ERROR:root:Could not send notifications.
Traceback (most recent call last):
  File "/home/giohappy/.virtualenvs/unesco-ihp/src/geonode/geonode/notifications_helper.py", line 95, in send_notification
    return notifications.models.send(*args, **kwargs)
  File "/home/giohappy/.virtualenvs/unesco-ihp/lib/python3.6/site-packages/pinax/notifications/models.py", line 198, in send
    return send_now(*args, **kwargs)
  File "/home/giohappy/.virtualenvs/unesco-ihp/lib/python3.6/site-packages/pinax/notifications/models.py", line 154, in send_now
    notice_type = NoticeType.objects.get(label=label)
  File "/home/giohappy/.virtualenvs/unesco-ihp/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/giohappy/.virtualenvs/unesco-ihp/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
pinax.notifications.models.NoticeType.DoesNotExist: NoticeType matching query does not exist.
The invited user "user.one" is not a member
WARNING:geonode.groups.models:The invited user "user.one" is not a member
```

**Comment by giohappy** [comment]
I needed to run a migrate to activate the new notice types

**Comment by MarcHKV** [comment]
> I needed to run a migrate to activate the new notice types

How do you 'run a migrate'?
