### ISSUE TITLE
URL sent by email for password reset doesn't work

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/unesco-ihp#338]
The link inside the password reset email returns an error page on dev server.

**Comment by afabiani** [comment]
The issue seems to be non-trivial. I see a stacktrace from `django-allauth` like the one here below:

```python
Internal Server Error: /account/password/reset/key/1f4-5os-4cc40a3c5136cdc1e9f6/
Traceback (most recent call last):
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/allauth/account/views.py", line 753, in dispatch
    if token_form.is_valid():
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/forms/forms.py", line 185, in is_valid
    return self.is_bound and not self.errors
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/forms/forms.py", line 180, in errors
    self.full_clean()
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/forms/forms.py", line 382, in full_clean
    self._clean_form()
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/django/forms/forms.py", line 409, in _clean_form
    cleaned_data = self.clean()
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/allauth/account/forms.py", line 611, in clean
    self.reset_user = self._get_user(uidb36)
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/allauth/account/forms.py", line 597, in _get_user
    pk = url_str_to_user_pk(uidb36)
  File "/home/geosolutions/.virtualenvs/geonode3/lib/python3.7/site-packages/allauth/account/utils.py", line 471, in url_str_to_user_pk
    pk_field = User._meta.pk.remote_field.to._meta.pk
AttributeError: 'OneToOneRel' object has no attribute 'to'
```

Probably the error is caused by the custom User model provided by the IHP instance, but at this moment I cannot really figure out what the real cause could be.

**Comment by afabiani** [comment]
Uhm it looks to be fixed already

https://github.com/pennersr/django-allauth/issues/2027

Still investigating...

**Comment by giohappy** [comment]
@afabiani if it's something affecting GeoNode in general ok, otherwise please put this on hold.
