### ISSUE TITLE
UTF-8 encoding issue with "french" based vector layers

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/unesco-ihp#98]
GeoNode is currently throwing the following encoding exception when uploading shapfiles or vectorial layers containing non UTF characters

Traceback (most recent call last):
  File "/home/geosolutions/work/repo/geonode/geonode/upload/views.py", line 595, in view
    Upload.objects.update_from_session(upload_session)
  File "/home/geosolutions/work/repo/geonode/geonode/upload/models.py", line 41, in update_from_session
    upload_session)
  File "/home/geosolutions/work/repo/geonode/geonode/upload/models.py", line 102, in update_from_session
    self.save()
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 83, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/operations.py", line 218, in last_executed_query
    return cursor.query.decode('utf-8')
  File "/home/geosolutions/.virtualenvs/geonode/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 7245: invalid continuation byte

**Comment by afabiani** [comment]
After further investigation, the issue seems to be related to non-ASCII characters on username which is now saved on the "Upload Session" thus conflicting with PostgreSQL Encoding.

**Comment by meyerch** [comment]
Problem solved, so I am archiving this one
